import 'package:flutter/material.dart';

enum ColorsEnum {
  red,
  green,
  blue,
  yellow,
  orange,
  purple,
  pink,
  brown,
  black,
  indigo,
  white,
  deepPurple,
  lightBlue,
  cyan,
  teal,
  lightGreen,
  lime,
  amber,
  deepOrange,
  grey,
  blueGrey,
  redAccent,
  pinkAccent,
  purpleAccent,
  deepPurpleAccent,
  indigoAccent,
  blueAccent,
  lightBlueAccent,
  cyanAccent,
  tealAccent,
  greenAccent,
  lightGreenAccent,
  limeAccent,
  yellowAccent,
  amberAccent,
  orangeAccent,
  deepOrangeAccent,
  transparent;
}

extension ColorExtension on ColorsEnum {
  Color color() {
    return switch (this) {
      ColorsEnum.red => Colors.red,
      ColorsEnum.green => Colors.green,
      ColorsEnum.blue => Colors.blue,
      ColorsEnum.yellow => Colors.yellow,
      ColorsEnum.orange => Colors.orange,
      ColorsEnum.purple => Colors.purple,
      ColorsEnum.pink => Colors.pink,
      ColorsEnum.brown => Colors.brown,
      ColorsEnum.black => Colors.black,
      ColorsEnum.indigo => Colors.indigo,
      ColorsEnum.white => Colors.white,
      ColorsEnum.deepPurple => Colors.deepPurple,
      ColorsEnum.lightBlue => Colors.lightBlue,
      ColorsEnum.cyan => Colors.cyan,
      ColorsEnum.teal => Colors.teal,
      ColorsEnum.lightGreen => Colors.lightGreen,
      ColorsEnum.lime => Colors.lime,
      ColorsEnum.amber => Colors.amber,
      ColorsEnum.deepOrange => Colors.deepOrange,
      ColorsEnum.grey => Colors.grey,
      ColorsEnum.blueGrey => Colors.blueGrey,
      ColorsEnum.redAccent => Colors.redAccent,
      ColorsEnum.pinkAccent => Colors.pinkAccent,
      ColorsEnum.purpleAccent => Colors.purpleAccent,
      ColorsEnum.deepPurpleAccent => Colors.deepPurpleAccent,
      ColorsEnum.indigoAccent => Colors.indigoAccent,
      ColorsEnum.blueAccent => Colors.blueAccent,
      ColorsEnum.lightBlueAccent => Colors.lightBlueAccent,
      ColorsEnum.cyanAccent => Colors.cyanAccent,
      ColorsEnum.tealAccent => Colors.tealAccent,
      ColorsEnum.greenAccent => Colors.greenAccent,
      ColorsEnum.lightGreenAccent => Colors.lightGreenAccent,
      ColorsEnum.limeAccent => Colors.limeAccent,
      ColorsEnum.yellowAccent => Colors.yellowAccent,
      ColorsEnum.amberAccent => Colors.amberAccent,
      ColorsEnum.orangeAccent => Colors.orangeAccent,
      ColorsEnum.deepOrangeAccent => Colors.deepOrangeAccent,
      _ => Colors.transparent,
    };
  }
}
